<a href="https://colab.research.google.com/github/iotparth/Movie-Review-Classifcation-Naive-Bayes/blob/master/MOVIE_REVIEW_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from nltk.corpus import movie_reviews

In [ ]:
movie_reviews.categories()

['neg', 'pos']

In [ ]:
movie_reviews.fileids()

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [ ]:
len(movie_reviews.fileids())

2000

In [ ]:
movie_reviews.words(movie_reviews.fileids()[5])

['capsule', ':', 'in', '2176', 'on', 'the', 'planet', ...]

In [ ]:
documents=[]
for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        documents.append((movie_reviews.words(fileid),category))
documents[0:5]

[(['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...], 'neg'),
 (['the', 'happy', 'bastard', "'", 's', 'quick', 'movie', ...], 'neg'),
 (['it', 'is', 'movies', 'like', 'these', 'that', 'make', ...], 'neg'),
 (['"', 'quest', 'for', 'camelot', '"', 'is', 'warner', ...], 'neg'),
 (['synopsis', ':', 'a', 'mentally', 'unstable', 'man', ...], 'neg')]

In [ ]:
import random
random.shuffle(documents)
documents[0:5]

[(['synopsis', ':', 'nice', 'girl', 'susanne', 'has', ...], 'neg'),
 (['there', 'was', 'probably', 'a', 'good', 'reason', ...], 'neg'),
 (['mary', 'norton', "'", 's', 'children', "'", 's', ...], 'pos'),
 (['in', 'the', 'line', 'of', 'duty', 'is', 'the', ...], 'neg'),
 (['along', 'his', 'carreer', ',', 'mel', 'gibson', ...], 'pos')]

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [ ]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
import string
punctuations=list(string.punctuation)
stop=stop+punctuations
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
from nltk import pos_tag

In [ ]:
#### now we have to clean the file
def clean_reviews(words):
    output_words=[]
    for w in words:
        if w.lower() not in stop:
            pos=pos_tag([w])
            clean_word=lemmatizer.lemmatize(w,pos=get_simple_pos(pos[0][1]))
            output_words.append(clean_word.lower())
    return output_words

In [ ]:
documents=[(clean_reviews(document),category) for document,category in documents]

In [ ]:
documents[0]

(['synopsis',
  'nice',
  'girl',
  'susanne',
  'sex',
  'boyfriend',
  'daniel',
  'car',
  'visit',
  'daniel',
  'rich',
  'family',
  'thanksgiving',
  'mansion',
  'middle',
  'nowhere',
  'sex',
  'daniel',
  'basement',
  'susanne',
  'daniel',
  'must',
  'decide',
  'hide',
  'evil',
  'art',
  'thief',
  'shoot',
  'everyone',
  'else',
  'mansion',
  'steal',
  'painting',
  'brace',
  'one',
  'painfully',
  'obvious',
  'surprise',
  'ending',
  'comment',
  'thanksgiving',
  'time',
  'love',
  'one',
  'enjoy',
  'good',
  'home',
  'cooked',
  'meal',
  'maker',
  'body',
  'count',
  'however',
  'thanksgiving',
  'time',
  'multiple',
  'murder',
  'violence',
  'profanity',
  'family',
  'dysfunction',
  'sex',
  'boy',
  'feel',
  'well',
  'sat',
  'crap',
  'alyssa',
  'milano',
  'former',
  'child',
  'star',
  'bos',
  'matures',
  'make',
  'video',
  'sludge',
  'like',
  'movie',
  'someone',
  'somewhere',
  'thought',
  'great',
  'idea',
  'pair',
  'rap

In [ ]:
training_documents=documents[0:1500]
testing_documents=documents[1500:]

In [ ]:
all_words=[]
for doc in training_documents:
    all_words+=doc[0]

In [ ]:
import nltk

In [ ]:
freq=nltk.FreqDist(all_words)
common=freq.most_common(3000)
features=[i[0] for i in common]

In [ ]:
features

['film',
 'movie',
 'one',
 'make',
 'like',
 'character',
 'get',
 'see',
 'go',
 'time',
 'well',
 'scene',
 'even',
 'good',
 'story',
 'take',
 'would',
 'much',
 'bad',
 'come',
 'life',
 'also',
 'give',
 'two',
 'seem',
 'look',
 'way',
 '--',
 'first',
 'end',
 'know',
 'year',
 'work',
 'thing',
 'play',
 'plot',
 'say',
 'really',
 'show',
 'little',
 'people',
 'could',
 'man',
 'love',
 'great',
 'never',
 'director',
 'star',
 'best',
 'performance',
 'new',
 'try',
 'many',
 'big',
 'want',
 'actor',
 'u',
 'action',
 'find',
 'watch',
 'role',
 'act',
 'another',
 'think',
 'audience',
 'world',
 'something',
 'back',
 'day',
 'still',
 'turn',
 'set',
 'old',
 'however',
 'use',
 'part',
 'begin',
 'comedy',
 'real',
 'cast',
 'though',
 'feel',
 'guy',
 'interest',
 'last',
 'point',
 'every',
 'enough',
 'around',
 'young',
 'run',
 'write',
 'may',
 'effect',
 'script',
 'name',
 'almost',
 'right',
 'fact',
 'actually',
 'long',
 'since',
 'minute',
 'nothing',
 'wo

In [ ]:
def get_feature_dict(words):
    current_features={}
    word_set=set(words)
    for w in features:
        current_features[w]=w in word_set
    return current_features

In [ ]:
training_data=[(get_feature_dict(doc),category) for doc, category in training_documents]
testing_data=[(get_feature_dict(doc),category) for doc, category in training_documents]

In [ ]:
training_data[0]

({'film': True,
  'movie': True,
  'one': True,
  'make': True,
  'like': True,
  'character': False,
  'get': False,
  'see': True,
  'go': True,
  'time': True,
  'well': True,
  'scene': True,
  'even': False,
  'good': True,
  'story': False,
  'take': False,
  'would': False,
  'much': False,
  'bad': False,
  'come': False,
  'life': False,
  'also': False,
  'give': False,
  'two': False,
  'seem': False,
  'look': True,
  'way': False,
  '--': False,
  'first': False,
  'end': False,
  'know': False,
  'year': False,
  'work': False,
  'thing': False,
  'play': False,
  'plot': False,
  'say': True,
  'really': False,
  'show': True,
  'little': False,
  'people': True,
  'could': False,
  'man': False,
  'love': True,
  'great': True,
  'never': False,
  'director': False,
  'star': True,
  'best': False,
  'performance': False,
  'new': False,
  'try': True,
  'many': False,
  'big': False,
  'want': False,
  'actor': False,
  'u': True,
  'action': False,
  'find': False,
  

In [ ]:
from nltk import NaiveBayesClassifier

In [ ]:
classifier=NaiveBayesClassifier.train(training_data)

In [ ]:
nltk.classify.accuracy(classifier,testing_data)

0.8713333333333333

In [ ]:
classifier.show_most_informative_features(15)

Most Informative Features
               stupidity = True              neg : pos    =     10.4 : 1.0
                religion = True              pos : neg    =      9.6 : 1.0
                 idiotic = True              neg : pos    =      9.2 : 1.0
             outstanding = True              pos : neg    =      8.4 : 1.0
               ludicrous = True              neg : pos    =      8.3 : 1.0
                attorney = True              pos : neg    =      8.0 : 1.0
            breathtaking = True              pos : neg    =      8.0 : 1.0
                   anger = True              pos : neg    =      7.5 : 1.0
                   mulan = True              pos : neg    =      7.5 : 1.0
                  seagal = True              neg : pos    =      7.2 : 1.0
             wonderfully = True              pos : neg    =      6.7 : 1.0
               laughable = True              neg : pos    =      6.5 : 1.0
                   cindy = True              neg : pos    =      6.5 : 1.0

# Using Sklearn

In [ ]:
from sklearn.svm import SVC
from nltk.classify.scikitlearn import SklearnClassifier

In [ ]:
svc=SVC()

In [ ]:
classifier_sklearn=SklearnClassifier(svc)

In [ ]:
classifier_sklearn.train(training_data)

<SklearnClassifier(SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))>

In [ ]:
nltk.classify.accuracy(classifier_sklearn,testing_data)

0.86

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc=RandomForestClassifier()
classifier_sklearn1=SklearnClassifier(rfc)

In [ ]:
classifier_sklearn1.train(training_data)

<SklearnClassifier(RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))>

In [ ]:
nltk.classify.accuracy(classifier_sklearn1,testing_data)

0.9946666666666667

# count vectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
train_set={'The sky is blue','The sun is bright'}
count_vec=CountVectorizer(max_features=3)
a=count_vec.fit_transform(train_set)
print(a.todense())
a

[[1 1 1]
 [0 1 1]]


<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [ ]:
count_vec.get_feature_names()

['blue', 'is', 'the']

In [ ]:
categories=[category for document,category in documents]

In [ ]:
text_documents=[" ".join(document) for document,category in documents]

In [ ]:
text_documents[0]

'synopsis nice girl susanne sex boyfriend daniel car visit daniel rich family thanksgiving mansion middle nowhere sex daniel basement susanne daniel must decide hide evil art thief shoot everyone else mansion steal painting brace one painfully obvious surprise ending comment thanksgiving time love one enjoy good home cooked meal maker body count however thanksgiving time multiple murder violence profanity family dysfunction sex boy feel well sat crap alyssa milano former child star bos matures make video sludge like movie someone somewhere thought great idea pair rapper ice since guest star make sci fi channel series welcome paradox exactly win combination outside permanently ruin holiday else may say turkey well teach u beautiful attractive woman look strikingly like alyssa milano fall love nerd drive long wind road eye close complain english teacher present u heartwarming thanksgiving dinner attend alcoholic stuck rich white people wait black servant show u old guy try laugh sit arou

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(text_documents,categories)

In [ ]:
count_vec=CountVectorizer(max_features=2000,ngram_range=(1,2)) ### ngram_range= (min,max)
x_train_features=count_vec.fit_transform(x_train)
x_train_features

<1500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 260662 stored elements in Compressed Sparse Row format>

In [ ]:
x_train_features.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 2, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 2, 0]], dtype=int64)

In [ ]:
count_vec.get_feature_names()

['000',
 '10',
 '100',
 '13',
 '15',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '20',
 '30',
 '50',
 '60',
 '70',
 '80',
 '90',
 'abandon',
 'ability',
 'able',
 'absolutely',
 'academy',
 'accent',
 'accept',
 'accident',
 'accomplish',
 'achieve',
 'across',
 'act',
 'action',
 'action film',
 'action movie',
 'action scene',
 'action sequence',
 'actor',
 'actress',
 'actual',
 'actually',
 'ad',
 'adam',
 'adaptation',
 'add',
 'addition',
 'admit',
 'adult',
 'adventure',
 'affair',
 'affleck',
 'afraid',
 'african',
 'age',
 'agent',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aim',
 'air',
 'al',
 'alan',
 'alex',
 'alien',
 'alive',
 'allen',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'along way',
 'already',
 'also',
 'although',
 'always',
 'amaze',
 'america',
 'american',
 'among',
 'amount',
 'amuse',
 'amy',
 'anderson',
 'angel',
 'angle',
 'angry',
 'animal',
 'animate',
 'animation',
 'anna',
 'anne',
 'annie',
 'annoy',
 'another',
 'answer',
 'antho

In [ ]:
x_test_features=count_vec.transform(x_test)

In [ ]:
x_test_features

<500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 87223 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc=SVC()
svc.fit(x_train_features,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
svc.score(x_test_features,y_test)

0.824